         MACRO
         BLOCK
*        DSECT FOR I/O BLOCK
*        THIS BLOCK IS GENERATED BY COMPILER ON STACK
         SPACE
BLOCK    DSECT
BLKDFCB  DC    A(0)                    ADDR OF DFCB
BLKDDN   DC    0CL8' '                 DDNAME BEFORE OPEN
BLKLRECL DC    Y(0)                    RECORD LENGTH
         DC    AL1(0)                  SPACER
BLKSTAT  DC    AL1(0)                  STATUS BITS
BSLOCAL  EQU   X'40'                   THIS IS A LOCAL FILE
BSSTD    EQU   X'20'                   THIS IS STD INPUT OR OUTPUT FILE
BSPAGE   EQU   X'10'                   GIVE PAGE-SKIP NEXT PUT
BSWRITE  EQU   8                       WRITE STATUS, OPEN
BSREAD   EQU   4                       READ STATUS, OPEN
BSEOL    EQU   2                       END-OF-LINE
BSEOF    EQU   1                       END-OF-FILE
BLKNTB   DS    0C                      NON-TEXT BUFFER STARTS HERE
         SPACE
*        TEXTFILES USE FOLL 3 WORDS AS POINTERS
BLKPC    DC    A(0)                    CURRENT POSN IN BUFFER
BLKPE    DC    A(0)                    END OF BUFFER
BLKPS    DC    A(0)                    START OF BUFFER
*        THIS DESIGN DIFFERS FROM HIKITA'S; THESE POINTERS ARE ABSOLUTE
         MEND
