         MACRO
         PASDATA
*        COMMON COMMUNICATION AREA BETWEEN MODULES
PASDFLG  DC    0AL1(0)                 TIMER FLAG 80 WHEN IN EXECUTION
PASDLINK DC    A(0)                    LINKED LIST OF STEPNAMES
INDDNAM  DC    CL8' '
STAKHEAD DC    A(0)
HEAD     DC    A(0)                    START OF CODE
LENGTH   DC    A(0)                    LENGTH OF GETMAIN AREA
TAIL     DC    A(0)                    END OF GETMAIN, NPINIT
PASDTIM  DC    A(0)                    FOR STEP TIMING AND CLOCK FN
OLDPICA  DC    A(0)                    FOR SPIE
OUTDCB   DCB   MACRF=PM,DSORG=PS,DDNAME=SYSPRINT
         DC    A(0)                    SPARE
OUTBLK   DC    A(OUTDCB,0,0,0,OUTBUF)
SPIEL    SPIE  ,((1,13),15),MF=L
NFSBLKS  DC    A(4)                    DEFAULT NUMBER OF 2K BLOCKS FREE
NTRACE1  DC    A(5)                    NO OF INNER PROCS TO TRACE
NTRACE2  DC    A(5)                    NO OF OUTER PROCS TO TRACE
INTERVAL DC    F'1000000000'           FOR USE BY STIMER
         SPACE
         SPACE
DIRECTRY DS    0A
INITCNT  DC    A(0)
OBJLENG  DC    A(0)   LENGTH OF OBJECT CODE IN BYTES
PROCCNT  DC    A(0)  NUMBER OF PROC AND LONG JUMP ADDRS
ERRORS   DC    A(0)                    ZERO IF NO COMPILE-TIME ERRORS
         SPACE
PASFLINK DC    A(0)                    FOR LINKED LIST OF DCBS
         SPACE
SPIEOPSW DC    2A(0)
SPIEREGS DC    16A(0)
OUTBUF   DC    CL137' '
         MEND
